site_name: ULPatch Docs
site_url: https://rtoax.github.io/ulpatch/
repo_url: https://github.com/Rtoax/ulpatch
repo_name: Rtoax/ulpatch
copyright: Copyright &copy; 2021 - 2024 Rong Tao

nav:
  - Home: index.md

