name: docs
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'numpy>=1.17.0' \
                      'pyyaml>=5.3' \
                      'tqdm' \
                      'mkdocs>=1.5.2' \
                      'mkdocs-material>=9.2.6' \
                      'mkdocstrings[python]>=0.22.0' \
                      'mkdocs-static-i18n>=1.0.2' \
                      'mkdocs-include-markdown-plugin>=6.0.1'
      - name: Build site
        run: mkdocs build
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'Rtoax/ulpatch'
        run: mkdocs gh-deploy --force

